### ISSUE TITLE
Some don't work

### ISSUE THREAD

**Issue by Sauug** [rogeraabbccdd/CSGO-MVP#12]
Hello,

I do not understand why qaund I add certain songs does not work. Out of 39 songs there are about 5 that don't work. There is no capital letter to the mp3 file

**Comment by rogeraabbccdd** [comment]
- Make sure your sound format is correct.
- Make sure your path in config is correct.
- Make sure you have setup your fastdl server.
- Make sure you have upload sounds to both game server and fastdl.
- Make sure file is downloaded to client.

**Comment by Sauug** [comment]
Hello,

All is good, the files are in mp3 format out of the 10 added to the 29 files which all works only 4 works, while all the other songs work
