### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ferks-FK** [rogeraabbccdd/CSGO-MVP#17]
It would be very interesting to add a new cvar that would lock the volume.
Example: mvp_maxvol 0.5
This cvar would define that the volume 0.5 is the maximum that the customers can use, to avoid that they put the sounds at maximum, many use the volume at maximum, which is very irritating.

**Comment by rogeraabbccdd** [comment]
You can simply reduce the volume by any audio editor like Audicity, or change `mvp_defaultvol` cvar to 0.5
