### ISSUE TITLE
I can't get this plugin to work for me

### ISSUE THREAD

**Issue by Re-0x** [rogeraabbccdd/CSGO-MVP#18]
Well, I downloaded this plugin, put it on my server, made a fastdl with all the mvp songs, I just cant get them to work(for me)
I wanted to see what's the problem so I invited my friend to join. He said it's working for him. He also joined other servers with custom mvp's before joining mine, wich i didn't(if that matters)
I look to the console, they downloaded perfectly fine and I can find them in csgo/sound/mvp.
I got the server on Windoes 10(if that matters)

**Comment by crashzk** [comment]
If it hasn't solved for you, just make sure you have enabled the CSGO download settings.

**`cl_allowdownload 1; cl_allowupload 1; cl_downloadfilter all;`**

**Comment by rogeraabbccdd** [comment]
Close due to no feedback.
