### ISSUE TITLE
Force Mute valve music kits over  custom sound

### ISSUE THREAD

**Issue by rcon420** [rogeraabbccdd/CSGO-MVP#20]
Hey, I  sometimes hear the valve music kit in the background not always is there a way to force mute it while custom keeps playing? 

OFc person can go to their inventory and uncheck mark but that's too much asked from random players they might want their music kit in mm game so on.

**Comment by crashzk** [comment]
I believe the plugin already does this.

https://github.com/rogeraabbccdd/CSGO-MVP/blob/e98fe43107cf9ed79ac8023d243cdffbb91e6fd8/addons/sourcemod/scripting/kento_mvp.sp#L141-L143

**Comment by rogeraabbccdd** [comment]
Close due to inactive.
