### ISSUE TITLE
Issues With Songs

### ISSUE THREAD

**Issue by S1ncer3ly** [rogeraabbccdd/CSGO-MVP#21]
I cant add songs i downloaded a song and upload it to the server in songs/mvp and in the fastdl also and edit in the cfg file its appearing there but no sound is playing the bit rate of my song is 44.1 khz and 192 kbps please help !

**Comment by crashzk** [comment]
It would be nice if you could post server error logs, server console logs and even error logs on your console here.

Probably this is the reason, probably the audios you configured are not compatible. **Remember, CSGO only support MP3 44.1kHz**.

**Comment by rogeraabbccdd** [comment]
Close due to inactive.
