### ISSUE TITLE
Question with volume option

### ISSUE THREAD

**Issue by crashzk** [rogeraabbccdd/CSGO-MVP#27]
I wonder if there would be any difference between the player setting the volume to zero for MVP and disabling MVP.

Example would have a volume option from `0.1` to `1.0` and an option to completely disable MVP.

Menu would look like this:

- Option to choose MVP
- MVP volume
- Enable/Disable MVP

I ask because there are some players on my servers that ask how to disable MVP if they don't want to listen.

I think it would be just to leave the volume at zero, anyway, would there be any difference in these options? Would it be possible to implement?

Or would it just be the same thing as leaving the volume at zero.

**Comment by rogeraabbccdd** [comment]
There are 2 meanings of disable MVP.
- Mute all players' MVP anthem.
- Disable my MVP anthem.

Just simply set the volume to 0 if you don't want to hear others' MVP anthem.
