### ISSUE TITLE
Custom songs not downloading only johncena is downloading and playing

### ISSUE THREAD

**Issue by kartik6314** [rogeraabbccdd/CSGO-MVP#30]
SignalXWriteOpportunity(3)
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/hs.mp3.bz2.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/hs.mp3.bz2
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/hs.mp3.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/hs.mp3
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/illuminati.mp3.bz2.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/illuminati.mp3.bz2
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/illuminati.mp3.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/illuminati.mp3
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/SCOOP.mp3.bz2.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/SCOOP.mp3.bz2
Downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/SCOOP.mp3.
Error downloading https://fastdl.brosena.xyz/g_file/new//sound/mvp/SCOOP.mp3
No pure server whitelist. sv_pure = 0

**Comment by kartik6314** [comment]
i uploaded the files on my server its only playing john cena properly ....not  other cut and converted song ...i have converted the songs to 44.1khz  still facing these issue plz help

**Comment by rogeraabbccdd** [comment]
Your logs already told you what should you check.
