### ISSUE TITLE
warning 217: loose indentation

### ISSUE THREAD

**Issue by 925916995** [rogeraabbccdd/CSGO-MVP#33]
At compile time，else if(StrEqual(mvp_name, "random"))，Prompt:warning 217: loose indentation

**Comment by NaathySz** [comment]
- Loose identation is a normal warning. It means that you click "Space Bar" instead "Tab".
- Another thing that can cause this warning is Copy & Paste codes. 
- Dont do Shift+Enter to jump lines can cause this too.
Or just get codes that was already with this warning.

idk why this warning exist, but with or without, doesnt have difference. You dont need worry about this.

Anyway, if you have OCD and want code perfectly made without warnings like me, here is a "fix" 😅
[CSGO-MVP-master.zip](https://github.com/rogeraabbccdd/CSGO-MVP/files/9390840/CSGO-MVP-master.zip)

Ah, about this warning, here is a example:
if you get the warning on `line 20`, then probably you need go to `line 19`, remove start of line and press "tab".

You can go to start of `line 19` and press Back Space, then it will join with the line above, so you press Shift+Enter to jump line again. It will fix or change warning to line below. Then you just repeat proccess again, but with this line.

Im so bad to explain, but hope you understand ^^

**Comment by rogeraabbccdd** [comment]
Fixed.
