### ISSUE TITLE
Custom cut mp3 doesn't work 

### ISSUE THREAD

**Issue by phajtol** [rogeraabbccdd/CSGO-MVP#4]
Hello, 

I am having issue with the plugin. As the title says, it doesn't play my custom made mp3 sound.

I have setup fastdl, and files are all downloaded correctly, I also added the sound to the config and it appears in the menu, I can select it and everything. So I set my music to my file, win the round and the music doesn't play. There's an alert that my file is playing, so everything looks like it's set up correctly.

So suspect it's a problem with my file, because the default sounds play without any problem. Also, I mentioned that my file is cut to ~10 seconds from longer file, but when I play the original file everything is OK and it plays. I used Audacity for cutting, and then once again on a website https://mp3cut.net/, but in both cases result is the same. I also tried playing the file via console's command `play` and it played cut file without problem. It plays fine with windows' default player fine. So the problem is probably something with the file. Can you please help me?

If you need any further info let me know. I am also attaching both files.

[mvp.zip](https://github.com/rogeraabbccdd/CSGO-MVP/files/4143422/mvp.zip)

Thank you!

Regards
Peter Hajtol

**Comment by rogeraabbccdd** [comment]
Hi, your sounds are works in my test server.
Please make sure you have 
- Uploaded files to fastdl and your game server, and you can download it without problem. 
- Set file path in `kento_mvp.cfg` correctly.
- You are not setting mvp volume to 0.
