### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by golbanux** [rogeraabbccdd/CSGO-MVP#7]
Some people hears the MVP some not! Including me, i cant hear it on my sv but on others it works perfectly! A bit help? Golbanu#1337

**Comment by nguyenbaodanh** [comment]
same, some mp3 can play, some not, tried convert to different bitrate 128 96 64kbps but still not playing.

**Comment by nguyenbaodanh** [comment]
Test using sm_play to sound path , the music can play. So... I guess the plugin has limit for numbers of songs?

**Comment by rogeraabbccdd** [comment]
This is **NOT** plugin problem.
CSGO only supports 44.1khz mp3.
Please Google before you create issue.
