### ISSUE TITLE
Add cvar to leave a default volume for all players

### ISSUE THREAD

**Issue by crashzk** [rogeraabbccdd/CSGO-MVP#8]
Add cvar to leave a default volume for all players. Currently the default is `1.0`, it would be interesting if we could set a default for all players, if they want to, they change their volume.

**Comment by IshaanKr** [comment]
@rogeraabbccdd can I work on this issue? Please assign me.

**Comment by rogeraabbccdd** [comment]
Pull requests are always welcome.

**Comment by IshaanKr** [comment]
Thanks. 
I start working on it now. Please review pull request when I will create it.
